name: CMake and GTest CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive  # Автоматически подтягивает GTest из подмодулей

    - name: Configure CMake
      # Пробрасываем флаг, отключающий строгие варнинги для старого GTest
      run: cmake -H. -B_build -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS="-Wno-error=maybe-uninitialized"

    - name: Build Project
      run: cmake --build _build

    - name: Run Tests
      run: cmake --build _build --target test -- ARGS=--verbose
