name: CMake and GTest CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      # Убрали submodules: recursive, чтобы не падать на призраках старых лабораторных

    - name: Initialize GTest Submodule
      # Явно инициализируем и скачиваем ТОЛЬКО нужный нам Google Test
      run: |
        git submodule init third-party/gtest
        git submodule update third-party/gtest

    - name: Configure CMake
      run: cmake -H. -B_build -DBUILD_TESTS=ON -DCMAKE_CXX_FLAGS="-Wno-error=maybe-uninitialized"

    - name: Build Project
      run: cmake --build _build

    - name: Run Tests
      run: cmake --build _build --target test -- ARGS=--verbose
